<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Loops (Need) Exercises</span></div>

# Exercise 1

In [ ]:
import numpy as np                                      #using for and enumerate
temperatures_celsius = [
    0, 5, 10, 15, 20, 25,
    30, 35, 40, 45, 50
]

celcius_array = np.array(temperatures_celsius)

farenheit_array = celcius_array*9/5+32                  

farenheit_array

for index, celcius_temp in enumerate(celcius_array):       #index is a counting variable, defines celcius_temp as a variable in celcius_array, allows us to cycle thru celcius_array the number of times there are elements
    farenheit_temp = farenheit_array[index]                #allows us to cycle thru farenheit_array, where each element is farenheit_temp
    print(celcius_temp,',', farenheit_temp)                #prints

0 , 32.0
5 , 41.0
10 , 50.0
15 , 59.0
20 , 68.0
25 , 77.0
30 , 86.0
35 , 95.0
40 , 104.0
45 , 113.0
50 , 122.0


In [ ]:
import numpy as np                                      #using for and range
temperatures_celsius = [
    0, 5, 10, 15, 20, 25,
    30, 35, 40, 45, 50
]

celcius_array = np.array(temperatures_celsius)

farenheit_array = celcius_array*9/5+32

farenheit_array

for i in range(len(celcius_array)):
    celcius_temp1 = celcius_array[i]
    farenheit_temp1 = farenheit_temp
    print(f'{celcius_temp1}, {farenheit_temp1}')

0, 122.0
5, 122.0
10, 122.0
15, 122.0
20, 122.0
25, 122.0
30, 122.0
35, 122.0
40, 122.0
45, 122.0
50, 122.0


In [16]:
import numpy as np                                  #using while and f string
temperatures_celsius = [
    0, 5, 10, 15, 20, 25,
    30, 35, 40, 45, 50
]

celcius_array = np.array(temperatures_celsius)

farenheit_array = celcius_array*9/5+32

farenheit_array

index = len(temperatures_celsius)

while index != 0:
    print(f'{celcius_array}, {farenheit_array}')      #how to use while and loop thru the list?
    index -= 1

[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86.  95. 104. 113. 122.]
[ 0  5 10 15 20 25 30 35 40 45 50], [ 32.  41.  50.  59.  68.  77.  86

# Exercise 2

In [22]:
for letter in ['A', 'B', 'C']:
    for number in [1, 2, 3]:
        print(f'{letter}{number}', end='\t')
    print('\n')

A1	A2	A3	

B1	B2	B3	

C1	C2	C3	



In [ ]:
for count in [1,2,3,4,5]:                       #first layer: defines count list
    print(f'{count}', end=':')                  #prints the current count and ends such that python does not start new line
    for number in [1,2,3,4,5]:                  #second layer after printing current count: defines number list
        print(f'{count*number}', end='\t')      #prints the multiplied result and ends with tab to space them out, does so 5 times cuz of number
    print('\n')                                 #prints new line as second loop finishes once, finishing up the first loop once and repeats for number in count

1:1	2	3	4	5	

2:2	4	6	8	10	

3:3	6	9	12	15	

4:4	8	12	16	20	

5:5	10	15	20	25	



# Exercise 3

In [42]:
np.random.rand(10)

array([0.8679335 , 0.47768407, 0.60416001, 0.78155588, 0.40681886,
       0.56473058, 0.13079273, 0.24798378, 0.82088508, 0.66472478])

In [ ]:
experiment_number=1                                                                         #defines variable to be used later
for experiment in range(10):                                                                #loop 10 times
    results_array = np.random.rand(10)                                                      #runs rng 10 times and puts it in an array
    head_results_array = results_array[results_array>0.5]                                   #takes only heads in the array
    print(f'Experiment {experiment_number:>2}: No. of Heads = {len(head_results_array)}')   #prints the string and takes the no. of elements in the heads array
    experiment_number +=1                                                                   #increases the experiment no. and repeats after this

Experiment  1: No. of Heads = 4
Experiment  2: No. of Heads = 5
Experiment  3: No. of Heads = 5
Experiment  4: No. of Heads = 6
Experiment  5: No. of Heads = 3
Experiment  6: No. of Heads = 7
Experiment  7: No. of Heads = 8
Experiment  8: No. of Heads = 6
Experiment  9: No. of Heads = 2
Experiment 10: No. of Heads = 4


In [ ]:
results_array = np.random.rand(10)
head_results_array = results_array[results_array>0.5]
head_results_array
len(head_results_array)

7