<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

| Term       | Brief description |
|------------|-------------------|
| Subsetting |Accessing a portion of information out of a set|
| Indexing   |Accessing 1 unit of information in a set|
| Slicing    |Accessing more than 1 unit of information in a set|
| Masking    |Accessing information only meeting a certain criteria|

_Note: A more accurate description would be selecting one/multiple elements._   

# Exercise 2

In [ ]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2d[:,0]

int_array = np_array_2d[:,0].astype(int) #extracts numbers and converts them to integers to process them instead of them being in strings

remainder_array = int_array%2            #creates new array containing remainders after division by 2

remainder_array==1                       #checks whether remainder is 1

np_array_2d[remainder_array==1,1]        #the mask (remainder_array==1) results in elements being extracted when remainder is 1, the '1' after the comma directs the second item in the element to be extracted

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

# Exercise 3

In [2]:
import numpy as np

In [ ]:
start_array = np.array([[66, 50, 57, -1, -1],
                        [92, -1, 88, -1, -1],
                        [75, -1, -1, 76, -1],
                        [-1, 51, 87, -1, -1],
                        [71, -1, 67, -1, 69]])

start_array[start_array<50] = -1


array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [ ]:
start_array = np.array([[66, 50, 57, -1, -1],
                        [92, -1, 88, -1, -1],
                        [75, -1, -1, 76, -1],
                        [-1, 51, 87, -1, -1],
                        [71, -1, 67, -1, 69]])

neg_array = start_array[start_array<50]          # Generates an array that is of different dimension compared to start array
start_array[neg_array] = -1                      # This isn't a mask, its not really doing anything

pos_array = start_array[start_array>50]
start_array[pos_array] = 1                       #why does this not work? refer to above comments ^

start_array



IndexError: index 66 is out of bounds for axis 0 with size 5

In [ ]:
start_array = np.array([[66, 50, 57, -1, -1],
                        [92, -1, 88, -1, -1],
                        [75, -1, -1, 76, -1],
                        [-1, 51, 87, -1, -1],
                        [71, -1, 67, -1, 69]])  #creates array for use


start_array[start_array<50] = -1                #changes all elements that fit the condition to the corresponding value

start_array[start_array>50] = 1

start_array[start_array==50] = 0

start_array


array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])

In [ ]:
# Resolving comment
import numpy as np
start_array = np.array([[66, 50, 57, -1, -1],
                        [92, -1, 88, -1, -1],
                        [75, -1, -1, 76, -1],
                        [-1, 51, 87, -1, -1],
                        [71, -1, 67, -1, 69]])  #creates array for use

calc_array = start_array

calc_array[calc_array<50] = -1                #changes all elements that fit the condition to the corresponding value

calc_array[calc_array>50] = 1

calc_array[start_array==50] = 0               # This still works, probably because they are both the same size?

calc_array

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])